"""Generate version_info.txt (Windows version resource) for PyInstaller.

Reads the single source of truth (edge_multi.__version__) and writes a
PyInstaller-compatible version file. Run before building:
    python tools/make_version.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from edge_multi import __app_name__, __version__  # noqa: E402

OUT = ROOT / "version_info.txt"
EXE_NAME = "EdgeMultiProfile.exe"


def _version_tuple(text: str) -> tuple[int, int, int, int]:
    nums = [int(n) for n in re.findall(r"\d+", text)][:4]
    nums += [0] * (4 - len(nums))
    return tuple(nums)  # type: ignore[return-value]


def main() -> None:
    v = _version_tuple(__version__)
    vstr = ".".join(str(n) for n in v)
    content = f"""# UTF-8
# Auto-generated by tools/make_version.py - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={v},
    prodvers={v},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', '{__app_name__}'),
          StringStruct('FileDescription', '{__app_name__}'),
          StringStruct('FileVersion', '{vstr}'),
          StringStruct('InternalName', 'EdgeMultiProfile'),
          StringStruct('OriginalFilename', '{EXE_NAME}'),
          StringStruct('ProductName', '{__app_name__}'),
          StringStruct('ProductVersion', '{vstr}')
        ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    OUT.write_text(content, encoding="utf-8")
    print(f"Created {OUT} (version {vstr})")


if __name__ == "__main__":
    main()
